### ISSUE TITLE
Configure lookup paths for composes/from

### ISSUE THREAD

**Issue by dfreeman** [madyankin/postcss-modules#13] opened 2015-12-15 20:25 UTC
I'm still wrapping my head around the standard patterns for how PostCSS plugins consume configuration, but it doesn't look like there's currently a way to pass configuration through to `postcss-import` to configure the root and search path(s) for `composes foo from 'bar'` lookups.

Is this something that it would make sense to add, or am I missing something fundamental? I'm also happy to put together a PR if you have a form factor in mind for how you might want to consume such configuration.

**Comment by outpunk** [comment] 2015-12-16 07:16
Hi, thank you for the feedback. You have to use paths relative to the root path right now, but I'm going to fix that soon.

**Comment by outpunk** [comment] 2016-01-28 08:36
@hellosmithy, @dfreeman Fixed, the new version is published

**Comment by tarikihm** [comment] 2016-03-10 17:32
I am having s similar issue on version `0.4.0` (latest today on npm): 

```
{ [Error: ENOENT: no such file or directory, open '/Users/tarikansari/Workspace/sane-web/src/components/GenrePicker/theme/elements/button-dark']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/tarikansari/Workspace/sane-web/src/components/GenrePicker/theme/elements/button-dark' }
```

It is looking for the file next to the path of the file that includes the composes, instead of using the `path` option configured on postcss-import. I don't have this issue when using webpack/css-loader?modules as it used the resolves/root option of webpack to look into the correct paths for files.

How are we supposed to pass the include path to postcss-modules?

**Comment by outpunk** [comment] 2016-03-10 18:37
@tarikihm thank you for the feedback! Could you make a minimal reproduceable example, please?

**Comment by tarikihm** [comment] 2016-03-10 19:51
May not time to write one until a couple days, for now here is more information: this is related to `css-modules-loader-core` which uses `require.resolve()` to resolve import

The way other tools handle this: `css-loader` instead used the context of Webpack (it's a loader), and `postcss-import` accept a `path` option, which is probably the approach `postcss-modules` should take.

A quick hacky workaround for me was to add a symlink named `theme` pointing to `src/theme` into `node_modules`, however that is not all, `postcss-modules` then fails to resolves composes which omit the `.css` extension, which are properly resolved by both `postcss-import` and `css-loader`.

**Comment by tarikihm** [comment] 2016-03-10 20:27
Thank you @outpunk, you may also want to follow https://github.com/postcss/postcss/issues/240 where adding a path option to PostCSS is being discussed. This would allows you to make the new option invisible once PostCSS introduces this.

**Comment by bernardodiasc** [comment] 2016-08-05 21:46
I see this is an old issue, but since still open. This plugin solved this problem for me https://www.npmjs.com/package/postcss-modules-resolve-path

**Comment by FezVrasta** [comment] 2017-03-21 13:54
Is this issue under the radar?

**Comment by kamilic** [comment] 2021-07-18 11:15
Need this feature.

**Comment by madyankin** [comment] 2021-07-21 09:47
Added in #126

**Closed by madyankin** 2021-07-21 09:47 UTC
Labels: enhancement
